---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: src/data/site/main.js
  label: Site
  match: "**/*"
- type: directory
  path: src/data/blog
  label: Blog
  create: documents
  match: "**/*.md"
  templates:
  - blog-post
upload_dir: src/data/blog/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
