---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: src/data/article
  label: Articles
  create: all
  match: "**/*.md"
- type: directory
  path: src/data/blog
  label: Posts
  create: documents
  match: "**/*.md"
  templates:
  - blog-post
- type: heading
  label: Site Settings
- type: document
  path: src/data/site/main.json
  label: Information
- type: document
  path: src/data/site/navigation.json
  label: Navigation
- type: document
  path: src/data/site/social.json
  label: Social Links
upload_dir: src/data/blog/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
