---
label: Site Metadata
hide_body: true
fields:
- type: text
  name: siteName
  label: Site Name
- type: text
  name: siteDescription
  label: Site Description
  description: Tagline or description of your site
- type: text
  name: author
  label: Author
  description: Owner of your site
pages:
- src/data/site/main.json
